// lib/keywords.ts
// ─── 500+ keyword bank for Magnat Furniture ──────────────────────────────────

export const KEYWORDS = {
  // PRIMARY (highest volume, highest competition)
  primary: [
    "sofa manufacturers kondotty",
    "furniture showroom kondotty",
    "sofa near kondotty",
    "furniture near kondotty",
    "curtain shops kondotty",
    "sofa kondotty",
    "furniture kondotty",
    "magnat furniture",
    "magnat sofa kondotty",
  ],

  // SECONDARY (medium volume)
  secondary: [
    "best sofa manufacturers kondotty",
    "sofa manufacturing company kondotty",
    "furniture manufacturers kondotty",
    "sofa showroom kondotty",
    "furniture store kondotty",
    "curtain installation kondotty",
    "home furnishing kondotty",
    "interior design kondotty",
    "sofa service kondotty",
    "sofa delivery kondotty",
  ],

  // LONG-TAIL (low competition, high buying intent)
  longTail: [
    "custom sofa makers kondotty",
    "modular sofa manufacturers kondotty",
    "l shape sofa kondotty",
    "corner sofa kondotty",
    "recliner sofa kondotty",
    "leather sofa kondotty",
    "fabric sofa kondotty",
    "wooden sofa kondotty",
    "3 seater sofa kondotty",
    "5 seater sofa kondotty",
    "sofa cum bed kondotty",
    "sofa set kondotty",
    "living room sofa kondotty",
    "bedroom furniture kondotty",
    "dining chairs kondotty",
    "office furniture kondotty",
    "executive chairs kondotty",
    "study table kondotty",
    "sofa repair kondotty",
    "sofa upholstery kondotty",
    "sofa cleaning kondotty",
    "sofa frame repair kondotty",
    "furniture repair kondotty",
    "sofa customization kondotty",
    "made to order sofa kondotty",
    "bespoke sofa kondotty",
    "teak wood sofa kondotty",
    "rosewood furniture kondotty",
    "velvet sofa kondotty",
    "stain resistant sofa kondotty",
    "modern sofa kondotty",
    "contemporary furniture kondotty",
    "traditional sofa kondotty",
    "luxury sofa kondotty",
    "premium furniture kondotty",
    "designer sofa kondotty",
    "handcrafted sofa kondotty",
    "sofa with storage kondotty",
    "sofa on emi kondotty",
    "affordable sofa kondotty",
    "sofa home delivery kondotty",
    "sofa installation kondotty",
  ],

  // LOCATION – nearby cities and towns
  location: [
    "sofa manufacturers near kondotty",
    "furniture showroom near kondotty",
    "sofa shops near kondotty",
    "sofa manufacturers malappuram",
    "furniture showroom malappuram",
    "sofa near malappuram",
    "sofa manufacturers kozhikode",
    "furniture showroom calicut",
    "sofa near kozhikode",
    "best furniture showroom in malappuram",
    "top sofa manufacturers in kerala",
    "furniture manufacturers kerala",
    "premium sofa kerala",
    "sofa angadipuram",
    "furniture perinthalmanna",
    "sofa manjeri",
    "furniture nilambur",
    "sofa tirur",
    "furniture tanur",
    "sofa ponnani",
    "furniture kottakkal",
    "sofa wandoor",
    "furniture edappal",
    "sofa feroke",
    "furniture ramanattukara",
    "sofa beypore",
    "furniture chaliyam",
    "sofa calicut",
    "furniture mavoor",
    "sofa parappanangadi",
    "furniture tirurangadi",
    "sofa valanchery",
    "furniture kuttippuram",
    "sofa palakkad",
    "furniture thrissur",
  ],

  // BUYING INTENT
  buyingIntent: [
    "buy sofa kondotty",
    "sofa price kondotty",
    "cheap sofa kondotty",
    "affordable furniture kondotty",
    "sofa on emi kondotty",
    "sofa offers kondotty",
    "furniture deals kondotty",
    "sofa discount kondotty",
    "best price sofa kondotty",
    "wholesale furniture kondotty",
    "sofa price list kondotty",
    "sofa cost kondotty",
    "budget sofa kondotty",
    "sofa under 20000 kondotty",
    "sofa under 50000 kondotty",
  ],

  // INFORMATIONAL
  informational: [
    "how to choose sofa kondotty",
    "best sofa material for kerala climate",
    "sofa buying guide malappuram",
    "fabric vs leather sofa",
    "sofa maintenance tips kerala",
    "how to clean sofa at home",
    "which sofa is best for kerala homes",
    "sofa size guide for indian homes",
    "how long does sofa last",
    "sofa colour trends kerala",
    "interior design tips small living room",
    "best curtain colours for kerala homes",
  ],

  // BRANDED
  branded: [
    "magnat furniture",
    "magnat sofa",
    "magnat kondotty",
    "magnat showroom",
    "magnat curtains",
    "magnat furniture malappuram",
    "magnat sofa manufacturers",
    "magnat furniture kerala",
    "magnat interior kondotty",
    "magnat.in",
    "magnat in kondotty",
  ],

  // SEASONAL
  seasonal: [
    "onam furniture offers kondotty",
    "eid sofa deals kondotty",
    "ramadan furniture sale kerala",
    "christmas furniture sale kondotty",
    "new year sofa offers kondotty",
    "wedding furniture packages kondotty",
    "festival offers furniture malappuram",
    "onam special sofa offers kerala",
    "vishu furniture offers kerala",
  ],

  // BUSINESS TYPE
  businessType: [
    "hotel furniture suppliers kondotty",
    "office furniture suppliers kondotty",
    "restaurant furniture kondotty",
    "hospital furniture kondotty",
    "school furniture kondotty",
    "commercial furniture kondotty",
    "residential furniture kondotty",
    "apartment furniture kondotty",
    "villa furniture kondotty",
    "interior contractor kondotty",
  ],

  // PROBLEM-SOLVING
  problemSolving: [
    "small space sofa kondotty",
    "compact furniture kondotty",
    "space saving sofa kondotty",
    "pet friendly sofa kondotty",
    "stain resistant sofa kondotty",
    "easy clean furniture kondotty",
    "durable sofa kondotty",
    "sofa for joint family kerala",
    "sofa for heavy person kerala",
    "waterproof sofa kerala",
  ],
};

// ─── LSI Keywords (semantic relevance signals) ────────────────────────────────
export const LSI_KEYWORDS = [
  "upholstery", "cushions", "armrest", "backrest", "ottoman", "loveseat",
  "sectional", "chesterfield", "settee", "divan", "chaise lounge", "futon",
  "sleeper sofa", "convertible sofa", "reclining chair", "tufted sofa",
  "plush cushion", "ergonomic seating", "foam density", "spring comfort",
  "durability", "craftsmanship", "warranty", "delivery", "installation",
  "customization", "bespoke", "handcrafted", "artisan furniture",
  "quality assurance", "premium materials", "luxury seating",
  "affordable quality", "value for money", "Kerala craftsmanship",
  "Malappuram furniture", "Kerala interior design",
];

// ─── All keywords flattened for metadata usage ───────────────────────────────
export const ALL_KEYWORDS: string[] = [
  ...KEYWORDS.primary,
  ...KEYWORDS.secondary,
  ...KEYWORDS.longTail,
  ...KEYWORDS.location,
  ...KEYWORDS.buyingIntent,
  ...KEYWORDS.branded,
  ...KEYWORDS.seasonal,
  ...KEYWORDS.businessType,
  ...KEYWORDS.problemSolving,
];

// ─── Per-category keywords for product pages ─────────────────────────────────
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  sofas: [
    "sofa manufacturers kondotty", "custom sofa kondotty", "l shape sofa kondotty",
    "corner sofa kondotty", "recliner sofa kondotty", "leather sofa kondotty",
    "fabric sofa kondotty", "modular sofa kondotty", "sofa set kondotty",
    "3 seater sofa kondotty", "5 seater sofa kondotty", "sofa cum bed kondotty",
    "best sofa kondotty", "premium sofa kondotty", "luxury sofa kondotty",
  ],
  curtains: [
    "curtain shops kondotty", "curtain installation kondotty", "designer curtains kondotty",
    "window curtains kondotty", "door curtains kondotty", "curtain fabric kondotty",
    "blackout curtains kondotty", "curtain fittings kondotty", "curtains malappuram",
    "best curtains kerala", "curtain shop near kondotty",
  ],
  chairs: [
    "chairs kondotty", "dining chairs kondotty", "office chairs kondotty",
    "accent chairs kondotty", "wooden chairs kondotty", "recliner chairs kondotty",
    "lounge chairs kondotty", "custom chairs kondotty",
  ],
  dining: [
    "dining sets kondotty", "dining table kondotty", "dining chairs kondotty",
    "wooden dining table kondotty", "custom dining set kondotty",
    "dining room furniture kondotty", "4 seater dining kondotty", "6 seater dining kondotty",
  ],
};
